config/routes.rb
NearcutCodingChallenge::Application.routes.draw do
  root to: 'users#index'
  resources :users, only: %i[index create]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password

  validates :name, presence: true
  validates_with PasswordValidator

  class << self
    def create_from_csv!(name:, password:)
      user = User.create!(name: name, password: password)
      "#{user.name} was successfully created"
    rescue ActiveRecord::RecordInvalid => invalid
      invalid.record.errors.full_messages.first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @results = ::CsvImporter.new(params[:file]).import!
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NearcutCodingChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/_items.html.erb
<% if results.is_a?(String) %>
  <%= results %>
<% else %>
  <% results.each do |result| %>
    <p>
      <%= result %>
    </p>
  <% end %>
<% end %>

app/views/users/create.js.erb
$('#content-box').html("<%= j (render partial: 'items', locals: {results: @results}) %>")

app/views/users/index.html.erb
<%= form_tag users_path, multipart: true, remote: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<div id='content-box'>

</div>